[package]
name = "parralel_threads_computations"
version = "0.1.0"
authors = ["vass"]
edition = "2024"

[dependencies]
wgpu = "0.16"
pollster = "0.3"
env_logger = "0.9"
log = "0.4"
bytemuck = "1.14"
futures-intrusive = "0.4"
anyhow = "1.0.99"
glam = "0.30.5"
crossbeam = "0.8.4"
flume = "0.11.1"



